### ISSUE TITLE
There is a crash in datomic-pro service

### ISSUE THREAD

**Issue by dannypsnl** [Ramblurr/datomic-pro-flake#2]
## Config
The current config in my `configuration.nix` as below
```nix
 services.datomic-pro = {
    enable = true;
    secretsFile = config.sops.templates."datomic-secrets.properties".path;
    settings = {
      enable = true;
      host = "localhost";
      port = 4334;
      memory-index-max = "256m";
      memory-index-threshold = "32m";
      object-cache-max = "128m";
      protocol = "dev";
      storage-access = "remote";
    };
  };
  services.datomic-console = {
    enable = true;
    port = 8000;
    dbUriFile = config.sops.templates."datomic-secrets-dburi".path;
  };

  sops = {
    # ...
    secrets.admin-passwd = { sopsFile = ... };
    secrets.datomic-passwd = { sopsFile = ... };

    templates."datomic-secrets.properties" = {
      owner = "root";
      mode = "0600";
      content = ''
        storage-admin-password=${config.sops.placeholder.admin-passwd}
        storage-datomic-password=${config.sops.placeholder.datomic-passwd}
      '';
    };
    templates."datomic-secrets-dburi".content = "datomic:dev://localhost:4334/?password=${config.sops.placeholder.datomic-passwd}";
  };
```

## Error
After `nixos-rebuild` and start services, I got error messages `cannot connect to datomic:dev://localhost:4334/?password=..., please ensure transactor is running` when open `localhost:8000/browse` in browser, so I check the status of service then see

```
Aug 26 23:42:54 dannypsnl-nixos datomic-pro-start[2634935]:         at clojure.lang.MultiFn.invoke(MultiFn.java:234)
Aug 26 23:42:54 dannypsnl-nixos datomic-pro-start[2634935]:         at datomic.transactor$run_STAR_.invokeStatic(transactor.clj:364)
Aug 26 23:42:54 dannypsnl-nixos datomic-pro-start[2634935]:         at datomic.transactor$run_STAR_.invoke(transactor.clj:276)
Aug 26 23:42:54 dannypsnl-nixos datomic-pro-start[2634935]:         at datomic.transactor$run$fn__32833.invoke(transactor.clj:420)
Aug 26 23:42:54 dannypsnl-nixos datomic-pro-start[2634935]:         at clojure.core$binding_conveyor_fn$fn__5823.invoke(core.clj:2047)
Aug 26 23:42:54 dannypsnl-nixos datomic-pro-start[2634935]:         at clojure.lang.AFn.call(AFn.java:18)
Aug 26 23:42:54 dannypsnl-nixos datomic-pro-start[2634935]:         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
Aug 26 23:42:54 dannypsnl-nixos datomic-pro-start[2634935]:         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
Aug 26 23:42:54 dannypsnl-nixos datomic-pro-start[2634935]:         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
Aug 26 23:42:54 dannypsnl-nixos datomic-pro-start[2634935]:         at java.base/java.lang.Thread.run(Thread.java:1583)
```

## Information

OS: NixOS 24.05
arch: amd64

**Comment by Ramblurr** [comment]
Hi @dannypsnl 

I've had time to circle back to this project and really get it ready! Please check out the latest `main` branch, I will be pushing a `0.20` soon.



Some notes:

* remove the `enable` from settings


If you have any more issues please paste or upload more log lines. There wasn't that much to go on the first time.

**Comment by dannypsnl** [comment]
I use `0.3.0` now, sorry that the previous message is badly not full message of exception, the exception in datomic-pro service is here:
```
Terminating process - Error starting transactor
Nov 05 16:18:52 dannypsnl-nixos datomic-pro-start[1413687]: java.lang.RuntimeException: Unable to connect to embedded storage, make sure storage-admin-password is correct.
Nov 05 16:18:52 dannypsnl-nixos datomic-pro-start[1413687]:         at datomic.h2$init_embedded.invokeStatic(h2.clj:141)
Nov 05 16:18:52 dannypsnl-nixos datomic-pro-start[1413687]:         at datomic.h2$init_embedded.invoke(h2.clj:132)
Nov 05 16:18:52 dannypsnl-nixos datomic-pro-start[1413687]:         at datomic.h2$init_tcp.invokeStatic(h2.clj:154)
Nov 05 16:18:52 dannypsnl-nixos datomic-pro-start[1413687]:         at datomic.h2$init_tcp.invoke(h2.clj:150)
Nov 05 16:18:52 dannypsnl-nixos datomic-pro-start[1413687]:         at datomic.coordination$init_dev.invokeStatic(coordination.clj:51)
Nov 05 16:18:52 dannypsnl-nixos datomic-pro-start[1413687]:         at datomic.coordination$init_dev.invoke(coordination.clj:48)
Nov 05 16:18:52 dannypsnl-nixos datomic-pro-start[1413687]:         at datomic.coordination_ext$fn__19201.invokeStatic(coordination_ext.clj:99)
Nov 05 16:18:52 dannypsnl-nixos datomic-pro-start[1413687]:         at datomic.coordination_ext$fn__19201.invoke(coordination_ext.clj:97)
Nov 05 16:18:52 dannypsnl-nixos datomic-pro-start[1413687]:         at clojure.lang.MultiFn.invoke(MultiFn.java:234)
Nov 05 16:18:52 dannypsnl-nixos datomic-pro-start[1413687]:         at datomic.transactor$run_STAR_.invokeStatic(transactor.clj:383)
Nov 05 16:18:52 dannypsnl-nixos datomic-pro-start[1413687]:         at datomic.transactor$run_STAR_.invoke(transactor.clj:281)
Nov 05 16:18:52 dannypsnl-nixos datomic-pro-start[1413687]:         at datomic.transactor$run$fn__27801.invoke(transactor.clj:439)
Nov 05 16:18:52 dannypsnl-nixos datomic-pro-start[1413687]:         at clojure.core$binding_conveyor_fn$fn__5823.invoke(core.clj:2047)
Nov 05 16:18:52 dannypsnl-nixos datomic-pro-start[1413687]:         at clojure.lang.AFn.call(AFn.java:18)
Nov 05 16:18:52 dannypsnl-nixos datomic-pro-start[1413687]:         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
Nov 05 16:18:52 dannypsnl-nixos datomic-pro-start[1413687]:         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
Nov 05 16:18:52 dannypsnl-nixos datomic-pro-start[1413687]:         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
Nov 05 16:18:52 dannypsnl-nixos datomic-pro-start[1413687]:         at java.base/java.lang.Thread.run(Thread.java:1583)
```
Does this mean `storage-admin-password` has some limit or I use a wrong password?

I believe the exception is created when I'm using datomic-console to connect the DB.

**Comment by Ramblurr** [comment]
@dannypsnl please start by checking the files on disk for `config.sops.templates."datomic-secrets.properties".path` and `config.sops.templates."datomic-secrets-dburi".path`. Inspect their contents, does it look right?

**Comment by dannypsnl** [comment]
From my understanding, their content respectively should be
```
storage-admin-password=<secret1>
storage-datomic-password=<secret2>
```
and
```
datomic:dev://localhost:4334/?password=<secret2>
```
?

**Comment by Ramblurr** [comment]
@dannypsnl I'm running this nixos module without issue, I suspect this is a configuration error in your config somewhere. 

Please try and use [the nixos test in this repo](https://github.com/Ramblurr/datomic-pro-flake/blob/main/tests/nixos-module.nix) as a base, get it working, and then tweak it from there.

Unfortunately I don't have the bandwidth to help troubleshoot user's partial configs. If you can provide me a full config that I can copy+paste and run locally, I'd be happy to look into it further.
